# General metadata
site_name: Linum Framework Wiki

# GitHub repo settings
repo_url: https://github.com/Halatnikov/linum-framework
repo_name: Halatnikov/linum-framework
edit_uri: blob/master/docs/

# Theme edits
theme:
    name: material
    
    # feature flags
    features:
        - navigation.indexes

    # logo (this is dumb, but github doesn't want my pngs)
    logo: https://cdn.discordapp.com/attachments/406052265963683840/945003686151733299/linumlogo_ayleen-seraph.png
    favicon: https://cdn.discordapp.com/attachments/406052265963683840/945003686151733299/linumlogo_ayleen-seraph.png
    
    # colorschemes, dark is default
    palette:

        - scheme: slate
          primary: blue
          accent: blue
          toggle:
            icon: material/lightbulb-outline
            name: Switch to light mode

        - scheme: default
          primary: blue
          accent: blue
          toggle:
            icon: material/lightbulb
            name: Switch to dark mode
    
    # icons
    icon:
        repo: fontawesome/brands/github

# Custom plugins
plugins:
    - git-revision-date-localized

# --- Navigation bar ---
nav:
    - Index: index.md