## Linum Framework settings for Wiki
# https://squidfunk.github.io/mkdocs-material/setup/
# https://www.mkdocs.org/user-guide/configuration/

# General metadata
site_name: Linum Framework Wiki
#site_url: https://halatnikov.github.io/linum-framework/
copyright: idk

# GitHub repo settings
repo_url: https://github.com/Halatnikov/linum-framework/
repo_name: halatnikov/linum-framework
edit_uri: blob/master/docs/

# Extra
extra:
    social:
        - icon: material/web
          link: https://halatnikov.github.io/
          name: my "website"


# Theme edits
theme:
    name: material
    
    # feature flags
    features:
        - navigation.indexes
        - navigation.top
        - search.suggest
        - search.highlight

    # logo (this is stupid, but github doesn't want my pngs!!!)
    logo: https://cdn.discordapp.com/attachments/406052265963683840/945003686151733299/linumlogo_ayleen-seraph.png
    favicon: https://cdn.discordapp.com/attachments/406052265963683840/945003686151733299/linumlogo_ayleen-seraph.png
    
    # colorschemes, dark is default
    palette:

        - scheme: slate     # dark bg
          primary: blue
          accent: blue
          toggle:
            icon: material/lightbulb-outline
            name: Switch to light mode

        - scheme: default   # light bg
          primary: blue
          accent: blue
          toggle:
            icon: material/lightbulb
            name: Switch to dark mode
    
    # icons
    icon:
        repo: fontawesome/brands/github

# Plugins
plugins:
    - git-revision-date-localized
    - search:
        min_search_length: 2
    - tags:
        tags_file: special/tags.md

# Markdown extensions
# there's a lot, but how could i not??
markdown_extensions:
    # BUILT-IN
    - meta                  # add .yml at the start of page to customise stuff (use with tags plugin to do tags)
    - footnotes:            # footnote[^1] and [^1]: it's content
        PLACE_MARKER: [FOOTNOTES]
    - def_list              # `word` : definition
    - abbr                  # *[SCA]: Super Cool Abbreviation
    - admonition            # !!! Note! and there's like an icon and color
    - attr_list             # [Can do buttons](){ .md-button } and also { align=right } images
    - md_in_html            # image caption <figcaption> and idk, other html stuff
    - toc:                  # table of contents, get links to headers/sections
        title: 'Table of contents:'
        permalink: true
        baselevel: 2
        toc_depth: 3
    - tables                # well tables |:-:|-|
    
    # SUPPORTED
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.tasklist:    # - [x] checkmarks
        custom_checkbox: true
    - pymdownx.snippets     # --8<-- "snippet", can embed external files (use with abbr to add glossary)
    - pymdownx.caret        # ^^underscores^^ and ^small\ up\ symbols^
    - pymdownx.mark         # ==fill with yellow==
    - pymdownx.tilde        # ~~striked-through~~ and ~small\ down\ symbols~
    - pymdownx.critic       # {--red--} {++green++} {==yellow==} {>>comment<<} can do blocks too
    - pymdownx.keys         # keyboard keys ++ctrl+alt+del++
    - pymdownx.details      # ??? collapsible blocks, + to open (use with admonition)
    - pymdownx.emoji:       # :emoji: and mkdocs icons :material/lightbulb-outline: and custom too??
        emoji_index: !!python/name:materialx.emoji.twemoji 
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.smartsymbols
    - pymdownx.tabbed:
        alternate_style: true 
     
    # EXPERIMENTAL
    - smarty:
        smart_angled_quotes: true
    - nl2br
    - sane_lists
    - pymdownx.progressbar  # progress bar [=start% "end%"]{: .thin} or {: .candystripe} (with attr_list)
    - pymdownx.magiclink:
        hide_protocol: true
        repo_url_shortener: true
        repo_url_shorthand: true
        social_url_shortener: true
        social_url_shorthand: true
        user: halatnikov
        repo: linum-framework
    - pymdownx.escapeall
    - pymdownx.saneheaders
    - pymdownx.pathconverter:
        base_path: /linum-framework/
        absolute: true
        

# --- Navigation bar ---
nav:
    - index.md
    - Special pages:
        - special/tags.md
        - special/markdown.md
