## Linum Framework settings for Wiki
# https://squidfunk.github.io/mkdocs-material/setup/
# https://www.mkdocs.org/user-guide/configuration/

# General metadata
site_name: Linum Framework Wiki
#site_url: https://halatnikov.github.io/linum-framework/
copyright: idk

# GitHub repo settings
repo_url: https://github.com/Halatnikov/linum-framework/
repo_name: halatnikov/linum-framework
edit_uri: blob/master/docs/

# Extra
extra:
    social:
        - icon: material/web
          link: https://halatnikov.github.io/
          name: my "website"


# Theme edits
theme:
    name: material
    
    # feature flags
    features:
        - content.code.annotate
        - navigation.indexes
        - navigation.top
        - search.highlight
        - search.suggest

    # logo (this is stupid, but github doesn't want my pngs!!!)
    logo: https://cdn.discordapp.com/attachments/406052265963683840/945003686151733299/linumlogo_ayleen-seraph.png
    favicon: https://cdn.discordapp.com/attachments/406052265963683840/945003686151733299/linumlogo_ayleen-seraph.png
    
    # colorschemes, dark is default
    palette:

        - scheme: slate     # dark bg
          primary: blue
          accent: blue
          toggle:
            icon: material/lightbulb-outline
            name: Switch to light mode

        - scheme: default   # light bg
          primary: blue
          accent: blue
          toggle:
            icon: material/lightbulb
            name: Switch to dark mode
    
    # icons
    icon:
        repo: fontawesome/brands/github

# Plugins
plugins:
    - git-revision-date-localized
    - search:
        min_search_length: 2
    - tags:
        tags_file: special/tags.md

# Extra JS
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js     #sort tables

# Markdown extensions
# there's a lot, but how could i not??
markdown_extensions:
    # BUILT-IN
    - abbr                  # *[SCA]: Super Cool Abbreviation, but can be any words
    - admonition            # !!! note "Note!" and there's like an icon and different colors
    - attr_list             # [Can do buttons](){ .md-button } and also { align=right } images
    - def_list              # `word` : definition
    - footnotes:            # footnote[^1] and [^1]: it's content, insert [FOOTNOTES] to place anywhere
        PLACE_MARKER: [FOOTNOTES]
    - md_in_html            # image caption <figcaption> and idk, other html stuff
    - meta                  # add variables at start of file to customise stuff (use with tags plugin to do tags)
    - tables                # well tables |:-:|-|
    - toc:                  # table of contents, get links to headers/sections, insert [TOC] to place anywhere
        title: 'Table of contents:'
        permalink: true
        baselevel: 2
        toc_depth: 3
    
    # SUPPORTED
    - pymdownx.betterem:    # improvements for **formatting** to allow stacking and escaping
        smart_enable: all
    - pymdownx.caret        # ^^underscores^^ and ^small\ up\ symbols^
    - pymdownx.critic       # {--red--} {++green++} {==yellow==} {>>comment<<} can do blocks too
    - pymdownx.details      # ??? "collapsible blocks", ???+ to open (use with admonition)
    - pymdownx.emoji:       # :emoji: and mkdocs icons :material-lightbulb-outline: (/ with -) and custom too??
        emoji_index: !!python/name:materialx.emoji.twemoji 
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight:    # syntax highlighting in code blocks, line numbers
        anchor_linenums: true
    - pymdownx.inlinehilite # also highlights syntax in `inline code blocks`
    - pymdownx.keys         # keyboard keys ++ctrl+alt+del++
    - pymdownx.mark         # ==fill with color==
    - pymdownx.smartsymbols # replaces symbols for you: (tm) (c) (r), c/o +/- =/=, --> <-- <-->, 1/2, 1st 2nd 5th
    - pymdownx.snippets     # --8<-- "path", can embed external files (use with abbr to add glossary)
    - pymdownx.superfences: # allows nesting of elements in other elements (can do diagrams and etc with mermaid) 
        preserve_tabs: true
    - pymdownx.tabbed:      # === "tabs"
        alternate_style: true
    - pymdownx.tasklist:    # - [x] checkmarks
        custom_checkbox: true
    - pymdownx.tilde        # ~~striked-through~~ and ~small\ down\ symbols~
     
    # EXPERIMENTAL
    - nl2br                 # snaps markdown rules in half by not requiring a new paragraph everytime
    - sane_lists            # makes (un)ordered lists more manageable and also being able to start not from 1
    - smarty:               # replaces symbols for you: << >>, ..., -- ---
        smart_quotes: false
        smart_angled_quotes: true
    - pymdownx.escapeall    # you can escape any character with \, even \\
    - pymdownx.magiclink:   # formats regular links, also adds syntax for github and social(twitter) links
        hide_protocol: true
        repo_url_shortener: true
        repo_url_shorthand: true
        social_url_shortener: true
        social_url_shorthand: true
        user: halatnikov
        repo: linum-framework
    - pymdownx.progressbar  # progress bar [=start% "end%"]{: .thin} or {: .candystripe} (with attr_list)
    - pymdownx.saneheaders  # makes it so github issues don't detect as a header
        

# --- Navigation bar ---
nav:
    - index.md
    - Special pages:
        - special/tags.md
        - special/markdown.md
