# General metadata
site_name: Linum Framework Wiki

# GitHub repo settings
repo_url: https://github.com/Halatnikov/linum-framework
repo_name: Halatnikov/linum-framework
edit_uri: blob/master/docs/

announce: test

# Theme edits
theme:
    name: material
    
    # feature flags
    features:
        - navigation.indexes
        - navigation.top
        - search.suggest
        - search.highlight

    # logo (this is stupid, but github doesn't want my pngs!!!)
    logo: https://cdn.discordapp.com/attachments/406052265963683840/945003686151733299/linumlogo_ayleen-seraph.png
    favicon: https://cdn.discordapp.com/attachments/406052265963683840/945003686151733299/linumlogo_ayleen-seraph.png
    
    # colorschemes, dark is default
    palette:

        - scheme: slate
          primary: blue
          accent: blue
          toggle:
            icon: material/lightbulb-outline
            name: Switch to light mode

        - scheme: default
          primary: blue
          accent: blue
          toggle:
            icon: material/lightbulb
            name: Switch to dark mode
    
    # icons
    icon:
        repo: fontawesome/brands/github

# Custom plugins
plugins:
    - git-revision-date-localized
    - search
    - tags:
        tags_file: tags.md

markdown_extensions:
    - meta

# --- Navigation bar ---
nav:
    - index.md
    - tags.md