# version 3
name: mkdocs-material 
on:
  push:
    branches:
      - master 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#       --- fix for git-revision-date-localized ---
        with:
          fetch-depth: 0
#       --- fix for git-revision-date-localized --- 
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
#       --- additional plugins ---
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install markdown-grid-tables
#       --- additional plugins ---
      - run: mkdocs gh-deploy --force
